services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:80
    env_file:
      - ./frontend/.env
    environment:
      - VITE_WEBHOOK_URL=http://localhost:5678/webhook-test/schedule-exams
    depends_on:
      backend:
        condition: service_healthy

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@database:5432/exam-scheduling
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:3000/health').then(r => r.ok ? process.exit(0) : process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    container_name: database
    image: postgres:17
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=exam-scheduling
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d exam-scheduling"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - GENERIC_TIMEZONE=Asia/Bangkok
      - TZ=Asia/Bangkok
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  frontend_data:
  backend_data:
  db_data:
  n8n_data:

networks:
  default:
    driver: bridge